package validation

var messages = map[string]string{
	"default":     "{{.Attribute}} tidak valid",
	"required":    "{{.Attribute}} wajib diisi",
	"required_if": "{{.Attribute}} wajib diisi",
	"min":         "{{.Attribute}} harus lebih dari {{.Param}}",
	"max":         "{{.Attribute}} harus kurang dari {{.Param}}",
	"oneof":       "{{.Attribute}} harus salah satu dari {{.Param}}",
	"exist":       "{{.Attribute}} tidak ditemukan",
	"not_exist":   "{{.Attribute}} telah digunakan",
}

var attributes = map[string]string{
	"Name":         "Nama",
	"Code":         "Kode",
	"Price":        "Harga",
	"Company":      "Perusahaan",
	"Location":     "Lokasi",
	"Category":     "Kategori",
	"Unit":         "Satuan",
	"Transaction":  "Transaksi",
	"Address":      "Alamat",
	"Phonenumber":  "No Telepon",
	"Type":         "Tipe",
	"CashReceived": "Total Penerimaan",
	"Note":         "Catatan",
	"Profession":   "Pekerjaan",
	"Education":    "Pendidikan Terakhir",
	"Academic":     "Jadwal Akademik",
	"Classroom":    "Kelas",
	"Teacher":      "Guru",
	"Predicate":    "Predikat",
	"Session":      "Pertemuan",
	"StartDate":    "Tanggal Mulai",
	"EndDate":      "Tanggal Selesai",
	"Year":         "Tahun",
	"Assessments":  "Penilaian",
	"Assessment":   "Penilaian",
	"Attendance":   "Kehadiran",
	"Attendances":  "Kehadiran",
	"Score":        "Nilai",
	"Notes":        "Catatan",
	"Day":          "Hari",
	"Subject":      "Mata Pelajaran",
	"BirthPlace":   "Tempat Lahir",
	"BirthDate":    "Tanggal Lahir",
	"Schedule":     "Jadwal",
	"History":      "Riwayat",
	"Order":        "Urutan",
	"Date":         "Tanggal",
	"Chapter":      "Bab",
	"Page":         "Halaman",
	"Topic":        "Topik",
	"Gender":       "Jenis Kelamin",
	"Amount":       "Jumlah",
}
